use ncc;
CREATE TABLE college (CampusCode INT,CampusName varchar(20),CampusLocation varchar(255),CampusAddress varchar(255),PRIMARY KEY (CampusCode));
CREATE TABLE department (CampusCode INT,DepartmentCode INT,NameOfDepartment varchar(255),PRIMARY KEY (DepartmentCode),FOREIGN KEY (CampusCode) REFERENCES college(CampusCode));
CREATE TABLE historical_data (CampusCode INT,DepartmentCode INT,Year YEAR,Months varchar(20),Date DATE,Income FLOAT,EstablishmentPay FLOAT,VariablePay FLOAT,AgencyPay FLOAT,OtherPay FLOAT,TotalPay FLOAT,NonPay FLOAT,SurplusDeficit FLOAT,NoOfStudents INT,FOREIGN KEY (CampusCode) REFERENCES college(CampusCode),FOREIGN KEY (DepartmentCode) REFERENCES department(DepartmentCode));
INSERT INTO college (CampusCode, CampusName, CampusLocation, CampusAddress) VALUES (1, 'Redbridge', 'Chadwell Heath', 'RM6 4XT');
INSERT INTO college (CampusCode, CampusName, CampusLocation, CampusAddress) VALUES (2, 'Epping', 'Debden', 'IG10 3SA');
INSERT INTO college (CampusCode, CampusName, CampusLocation, CampusAddress) VALUES (3, 'Hackney', 'Hoxton', 'N1 6HQ');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (1, 1, 'Math');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (1, 2, 'English');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (1, 3, 'Science');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (1, 4, 'Media');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (2, 5, 'Construction');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (2, 6, 'Engineering');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (2, 7, 'Physics');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (2, 8, 'Broadcasting');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (3, 9, 'History');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (3, 10, 'Geography');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (3, 11, 'Economics');
INSERT INTO department (CampusCode, DepartmentCode, NameOfDepartment) VALUES (3, 12, 'Politics');